logLevel = "debug" # "debug" | "warn" | "error"
telemetry = false

[console]
depth = 50

[install]
exact = true
linker = "isolated"
cache.disable = false
install.registry = "https://registry.npmjs.org/"

[run]
silent = true
